name: Pull Data from Chicago Data Portal
on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 0 0 * *'
permissions:
  contents: write
jobs:
  download-data:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Download JSON data
        run:
          API_URL="https://data.cityofchicago.org/resource/bynn-gwxy.json?$limit=3"
          curl -sSL -o data.json API_URL
          
      - name: Commit JSON data
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          git add data.json
          git commit -m "Fetched JSON data"
          git push origin main