name: Pull Data from Chicago Data Portal
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
permissions:
  contents: write
jobs:
  download-data:
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip3 install requests sodapy

      - name: Run initial Python script
        run: python .github/workflows/access_api.py
        env:
          GIST_UPDATE_TOKEN: ${{ secrets.GIST_UPDATE_TOKEN }}
          SOCRATA_TOKEN: ${{ secrets.SOCRATA_TOKEN }}

      - name: Stage files and check for changes
        run: |
          git add data/bus.json data/lastModified.json
          if git diff --staged --quiet; then
            echo 'staged=false' >> $GITHUB_ENV
          else
            echo 'staged=true' >> $GITHUB_ENV
          fi

      - name: Install GDAL dependencies and run second script
        if: env.staged == 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgdal-dev gdal-bin
          pip3 install GDAL==3.4.1 bs4
          python .github/workflows/kmz_to_json.py

      - name: Stage map file
        if: env.staged == 'true'
        run: git add data/map.json

      - name: Commit and push changes
        if: env.staged == 'true'
        run: |
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "GitHub Action"
          git checkout test-branch
          git commit -m "automatically fetched update"
          git push origin test-branch

      - name: Build and deploy
        env:
          JAWG_TOKEN: ${{ secrets.JAWG_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git config user.name "GitHub Action"
          echo "REACT_APP_JAWG_TOKEN=$JAWG_TOKEN" > .env
          npm install
          npm run build
          echo "machine github.com login $GITHUB_TOKEN" > ~/.netrc
          npm run deploy